// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5PYS5UsDxNcZ9wUUR08Pmh3YlqrPCRck',
    appId: '1:90879726715:web:cb4defbf53514beb413ede',
    messagingSenderId: '90879726715',
    projectId: 'pacepal-7f5de',
    authDomain: 'pacepal-7f5de.firebaseapp.com',
    databaseURL: 'https://pacepal-7f5de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacepal-7f5de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQQLIwUTrvcpUT13XuK9OE7M_mqtgH7ZI',
    appId: '1:90879726715:android:f52582e14dbedf19413ede',
    messagingSenderId: '90879726715',
    projectId: 'pacepal-7f5de',
    databaseURL: 'https://pacepal-7f5de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacepal-7f5de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwYlZN7wF8Gz6KS_UnTOuErAm_Dxb_Vgw',
    appId: '1:90879726715:ios:68677bc3f421b612413ede',
    messagingSenderId: '90879726715',
    projectId: 'pacepal-7f5de',
    databaseURL: 'https://pacepal-7f5de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacepal-7f5de.appspot.com',
    iosBundleId: 'com.example.pacepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwYlZN7wF8Gz6KS_UnTOuErAm_Dxb_Vgw',
    appId: '1:90879726715:ios:68677bc3f421b612413ede',
    messagingSenderId: '90879726715',
    projectId: 'pacepal-7f5de',
    databaseURL: 'https://pacepal-7f5de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacepal-7f5de.appspot.com',
    iosBundleId: 'com.example.pacepal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5PYS5UsDxNcZ9wUUR08Pmh3YlqrPCRck',
    appId: '1:90879726715:web:9b35c943b9038569413ede',
    messagingSenderId: '90879726715',
    projectId: 'pacepal-7f5de',
    authDomain: 'pacepal-7f5de.firebaseapp.com',
    databaseURL: 'https://pacepal-7f5de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacepal-7f5de.appspot.com',
  );
}
